apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: lin-worker
  labels:
    name: lin-worker
    user: lin
spec:
  selector:
    matchLabels:
      name: lin-worker
  serviceName: lin-worker
  replicas: 8
  template:
    metadata:
      labels:
        name: lin-worker
        user: lin
    spec:
      # nodeSelector:
      #   cloud.google.com/gke-preemptible: "true"
      containers:
        - name: lin-worker
          image: itamtao/pytorch-mpi:cuda10
          imagePullPolicy: Always
          stdin: true
          tty: true
          command:
           - "/bin/bash"
           - "-c"
           - "--"
          args :
            - '/entrypoint.sh; /usr/local/bin/entrypoint.sh; sleep infinity'
          ports:
            - containerPort: 8888
              name: notebook
            - containerPort: 6006
              name: tensorboard
            - containerPort: 22
              name: ssh
          env:
            - name: ROLE
              value: "worker"
          resources:
            requests:
              nvidia.com/gpu: 4
            limits:
              nvidia.com/gpu: 4
          volumeMounts:
            - mountPath: /mlodata1
              name: my-pvc-nfs
            - mountPath: /dev/shm
              name: dshm
      volumes:
        - name: my-pvc-nfs
          persistentVolumeClaim:
            claimName: nfs
        - name: dshm
          emptyDir:
            medium: Memory
